Fix the plugin
membraneframework/membrane_ivf_plugin pull request #19
Opened 2024-06-18 14:10 UTC by Noarkhh

2024-06-27 08:06 UTC, varsill requested changes

2024-06-27 08:06 UTC, varsill commented on lib/membrane_ivf/serializer.ex
> +                spec: {non_neg_integer(), pos_integer()},
can it really be {0, <some positive number>}?

2024-06-27 09:55 UTC, Noarkhh commented on test/serializer_test.exs
> +      _number_of_frames::binary-size(4), _unused::binary-size(4)>> = file_header
now the element actually counts the number of frames processed and on eos seeks and updates this field. We assert on it later (lines 104-106)

2024-06-27 09:56 UTC, Noarkhh commented on test/integration_test.exs
>    defmodule TestPipeline do
no, forgor to remove

2024-06-28 15:34 UTC, varsill commented on test/serializer_test.exs
> +    buffers = Path.join(@fixtures_dir, "capture.dump") |> File.read!() |> :erlang.binary_to_term()
I cannot comment on line `132` of that file, but there are yet another some places where such a change with piping would be welcome ;)

2024-07-04 13:51 UTC, varsill approved these changes
🥇

2024-07-05 07:34 UTC, merged